name: Build Hello-World

on:
  push:
    branches:
      - main
    paths:
      - "ressources/s5/thomas-ca/projets/hello-world/**"

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Copy files
        run: |
          mkdir -p dist/s5/thomas-ca/projets/
          mv ressources/s5/thomas-ca/projets/hello-world/ dist/s5/thomas-ca/projets/hello-world/

      - name: Deploy to gh-pages
        run: |
          git fetch origin gh-pages
          git checkout gh-pages

          rsync -a dist/* ./
          rm -rf dist .astro

          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Update Hello-World site" || echo "No changes to commit"
          git push origin gh-pages
